name: moviefy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  http: ^0.12.2
  intl: ^0.16.1
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  flutter_spinkit: ^4.1.2+1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_launcher_name:
  name: "Moviefy"



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/